-- Create a table to store search history
create table searches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  query text not null,
  top_study_id text,
  synopsis_text text,
  num_studies_found int
);

-- Optional: Add a unique constraint to the query column to prevent duplicates at the DB level
-- alter table searches add constraint unique_query unique (query);
