-- Create a table to store search history
create table searches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  query text not null,
  top_study_id text,
  synopsis_text text,
  num_studies_found int
);

-- Enable Row Level Security (RLS) if you want to restrict access (optional for this demo)
-- alter table searches enable row level security;
